{
  imports = [
    ./avante.nix
    ./autopair.nix
    ./autosave.nix
    ./colorizer.nix
    ./direnv.nix
    ./floaterm.nix
    ./hardtime.nix
    ./harpoon.nix
    ./image.nix
    ./jupyter.nix
    ./last-place.nix
    ./markdown-preview.nix
    ./mini.nix
    ./navbuddy.nix
    ./neo-tree.nix
    ./neorg.nix
    # ./ollama.nix # require ollama services running.
    ./persistence.nix
    ./quarto.nix
    ./spectre.nix
    ./telescope.nix
    ./todo.nix
    ./ufo.nix
    ./undotree.nix
    ./wezterm.nix
    ./which-keys.nix
    ./wilder.nix
    ./yanky.nix
  ];
}
